=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://appliedenergistics.github.io/screen_style",
  "type": "object",
  "title": "AE2 Screen Style",
  "description": "Provides styling information for an AE2 UI screen",
  "required": [],
  "definitions": {
    "position": {
      "$comment": "Used to position an element in relationship to the size of the current dialog",
      "$id": "Position",
      "type": "object",
      "properties": {
        "left": {
          "type": "number",
          "description": "Positions the content to the right (positive) or left (negative) of the left screen edge."
        },
        "top": {
          "type": "number",
          "description": "Positions the content to the bottom (positive) or top (negative) of the top screen edge."
        },
        "right": {
          "type": "number",
          "description": "Positions the content to the left (positive) or right (negative) of the right screen edge."
        },
        "bottom": {
          "type": "number",
          "description": "Positions the content to the top (positive) or bottom (negative) of the bottom screen edge."
        }
      }
    },
    "color": {
      "$comment": "Definition of a color using a fake HTML notation",
      "type": "string",
      "pattern": "^#([0-9a-fA-F]{2}){3,4}$"
    },
    "text": {
      "$comment": "JSON schema definition of Minecraft text https://minecraft.wiki/w/Raw_JSON_text_format",
      "type": "object",
      "properties": {
        "extra": {
          "description": "Text that is displayed after this text, but that inherits this texts properties.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/text"
          }
        },
        "color": {
          "type": "string",
          "pattern": "^#([0-9a-fA-F]{6})$"
        },
        "font": {
          "type": "string",
          "default": "minecraft:default",
          "description": "Font in assets/<namespace>/font"
        },
        "bold": {
          "type": "boolean",
          "default": false
        },
        "italic": {
          "type": "boolean",
          "default": false
        },
        "underlined": {
          "type": "boolean",
          "default": false
        },
        "strikethrough": {
          "type": "boolean",
          "default": false
        },
        "obfuscated": {
          "type": "boolean",
          "default": false
        },
        "insertion": {
          "type": "string",
          "description": "When shift-clicked while the chat is open, the text of this property will be inserted."
        },
        "clickEvent": {
          "type": "object",
          "properties": {
            "action": {
              "type": "string",
              "enum": [
                "open_url",
                "open_file",
                "run_command",
                "suggest_command",
                "change_page",
                "copy_to_clipboard"
              ]
            },
            "value": {
              "type": "string"
            }
          },
          "required": ["action", "value"]
        },
        "hoverEvent": {
          "type": "object",
          "oneOf": [
            {
              "properties": {
                "action": {
                  "const": "show_text"
                },
                "contents": {
                  "$ref": "#/definitions/text"
                }
              }
            },
            {
              "properties": {
                "action": {
                  "const": "show_item"
                },
                "contents": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "default": "minecraft:air",
                      "description": "The item to show"
                    },
                    "count": {
                      "type": "integer",
                      "default": 1,
                      "description": "The item stack size"
                    },
                    "tag": {
                      "type": "string",
                      "description": "NBT of the item, serialized as string. See https://minecraft.wiki/w/Player.dat_format#Item_structure"
                    }
                  },
                  "required": ["id"]
                }
              }
            },
            {
              "properties": {
                "action": {
                  "const": "show_entity"
                },
                "contents": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "$ref": "#/definitions/text"
                    },
                    "type": {
                      "type": "string",
                      "default": "minecraft:pig",
                      "description": "The entity type id to show"
                    },
                    "id": {
                      "type": "string",
                      "description": "UUID of the entity to show"
                    }
                  }
                }
              }
            }
          ]
        }
      },
      "oneOf": [
        {
          "properties": {
            "text": {
              "description": "Display simple text",
              "type": "string"
            }
          },
          "required": ["text"]
        },
        {
          "properties": {
            "translate": {
              "description": "The ID of a translation key",
              "type": "string"
            },
            "with": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/text"
              }
            }
          },
          "required": ["translate"]
        },
        {
          "properties": {
            "keybind": {
              "type": "string",
              "description": "A keybind identifier"
            }
          },
          "required": ["keybind"]
        }
      ]
    },
    "rect": {
      "oneOf": [
        {
          "type": "array",
          "items": [
            {
              "type": "integer",
              "description": "x"
            },
            {
              "type": "integer",
              "description": "y"
            },
            {
              "type": "integer",
              "description": "width"
            },
            {
              "type": "integer",
              "description": "height"
            }
          ],
          "additionalItems": false
        },
        {
          "type": "object",
          "properties": {
            "x": {
              "type": "integer"
            },
            "y": {
              "type": "integer"
            },
            "width": {
              "type": "integer"
            },
            "height": {
              "type": "integer"
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "blitter": {
      "type": "object",
      "properties": {
        "texture": {
          "type": "string"
        },
        "textureWidth": {
          "type": "integer",
          "default": 256
        },
        "textureHeight": {
          "type": "integer",
          "default": 256
        },
        "srcRect": {
          "$ref": "#/definitions/rect"
        }
      },
      "required": ["texture"]
    },
    "generatedBackground": {
      "type": "object",
      "properties": {
        "width": {
          "type": "integer"
        },
        "height": {
          "type": "integer"
        }
      },
      "required": ["width", "height"]
    }
  },
  "properties": {
    "includes": {
      "description": "Relative path to other files to include before processing this one.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "palette": {
      "$comment": "See PaletteColor enum",
      "type": "object",
      "description": "Defines colors used through the UI screen",
      "properties": {
        "DEFAULT_TEXT_COLOR": {
          "$ref": "#/definitions/color"
        },
        "MUTED_TEXT_COLOR": {
          "$ref": "#/definitions/color"
        },
        "SELECTION_COLOR": {
          "$ref": "#/definitions/color"
        },
        "TEXTFIELD_PLACEHOLDER": {
          "$ref": "#/definitions/color"
        },
        "TEXTFIELD_SELECTION": {
          "$ref": "#/definitions/color"
        },
        "TEXTFIELD_ERROR": {
          "$ref": "#/definitions/color"
        },
        "TEXTFIELD_TEXT": {
          "$ref": "#/definitions/color"
        },
        "ERROR": {
          "$ref": "#/definitions/color"
        },
        "WHITE": {
          "$ref": "#/definitions/color"
        },
        "ANALYSER_NORMAL_NODES": {
          "$ref": "#/definitions/color"
        },
        "ANALYSER_DENSE_NODES": {
          "$ref": "#/definitions/color"
        },
        "ANALYSER_MISSING_NODES": {
          "$ref": "#/definitions/color"
        }
      }
    },
    "background": {
      "$ref": "#/definitions/blitter"
    },
    "generatedBackground": {
      "$ref": "#/definitions/generatedBackground"
    },
    "slots": {
      "type": "object",
      "description": "Defines positions for slots and their grid alignment",
      "additionalProperties": {
        "type": "object",
        "allOf": [
          {
            "properties": {
              "grid": {
                "$comment": "Configures the slots with this semantic in a grid",
                "enum": [
                  "IO_BUS_CONFIG",
                  "BREAK_AFTER_9COLS",
                  "BREAK_AFTER_2COLS",
                  "BREAK_AFTER_3COLS",
                  "HORIZONTAL",
                  "VERTICAL"
                ]
              }
            }
          },
          {
            "$ref": "#/definitions/position"
          }
        ]
      },
      "propertyNames": {
        "$comment": "List SlotSemantic names here",
        "enum": [
          "NONE",
          "STORAGE",
          "PLAYER_INVENTORY",
          "PLAYER_HOTBAR",
          "TOOLBOX",
          "CONFIG",
          "UPGRADE",
          "STORAGE_CELL",
          "INSCRIBER_PLATE_TOP",
          "INSCRIBER_PLATE_BOTTOM",
          "MACHINE_INPUT",
          "MACHINE_PROCESSING",
          "MACHINE_OUTPUT",
          "MACHINE_CRAFTING_GRID",
          "CANER_CONTENT",
          "CANER_CONTAINER",
          "BLANK_PATTERN",
          "ENCODED_PATTERN",
          "PATTERN_MODIFIER_PANEL",
          "PATTERN_MODIFIER_TARGET",
          "PATTERN_MODIFIER_CLONE",
          "PATTERN_MODIFIER_BLANKS",
          "PATTERN_MODIFIER_REPLACE_TARGET",
          "PATTERN_MODIFIER_REPLACE_WITH",
          "VIEW_CELL",
          "MAGNET_PICKUP_CONFIG",
          "MAGNET_INSERT_CONFIG",
          "WIRELESS_SINGULARITY",
          "CRAFTING_GRID",
          "CRAFTING_RESULT",
          "PROCESSING_INPUTS",
          "PROCESSING_OUTPUTS",
          "MISSING_INGREDIENT"
        ]
      }
    },
    "text": {
      "description": "Defines text that will be shown on the UI, the property name is used to reference text from code",
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "text": {
            "$ref": "#/definitions/text"
          },
          "color": {
            "$comment": "See enum PaletteColor",
            "enum": [
              "DEFAULT_TEXT_COLOR",
              "MUTED_TEXT_COLOR",
              "SELECTION_COLOR",
              "ERROR",
              "WHITE",
              "ANALYSER_NORMAL_NODES",
              "ANALYSER_DENSE_NODES",
              "ANALYSER_MISSING_NODES"
            ],
            "default": "DEFAULT_TEXT_COLOR"
          },
          "position": {
            "$ref": "#/definitions/position"
          },
          "scale": {
            "type": "number",
            "default": 1,
            "minimum": 0.1,
            "maximum": 4,
            "$comment": "Can be used to display smaller text, 0.5 works well, usually"
          },
          "align": {
            "type": "string",
            "default": "LEFT",
            "enum": ["LEFT", "CENTER", "RIGHT"]
          },
          "maxWidth": {
            "type": "number",
            "minimum": 0,
            "default": 0,
            "description": "If greater than 0, the text will be word-wrapped when it reaches the given width in pixels."
          }
        }
      }
    },
    "tooltips": {
      "description": "Defines areas that will show a tooltip on the screen. These areas are evaluated after everything else that could show a tooltip.",
      "type": "object",
      "additionalProperties": {
        "allOf": [
          {
            "type": "object",
            "properties": {
              "tooltip": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/text"
                }
              },
              "width": {
                "type": "integer"
              },
              "height": {
                "type": "integer"
              }
            },
            "required": ["tooltip", "width", "height"]
          },
          {
            "$ref": "#/definitions/position"
          }
        ]
      }
    },
    "images": {
      "description": "Additional screen-specific images",
      "additionalProperties": {
        "$ref": "#/definitions/blitter"
      }
    },
    "terminalStyle": {
      "description": "If this screen is a terminal, this defines required properties to display it properly",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "header": {
          "description": "The top of the terminal background right up to the first row of content.",
          "$ref": "#/definitions/blitter"
        },
        "firstRow": {
          "description": "The area to draw for the first row in the terminal. Usually this includes the top of the scrollbar.",
          "$ref": "#/definitions/blitter"
        },
        "row": {
          "description": "The area to repeat for every row in the terminal. Should be 16px for the item + 2px for the border in size.",
          "$ref": "#/definitions/blitter"
        },
        "lastRow": {
          "description": "The area to draw for the last row in the terminal. Usually this includes the top of the scrollbar.",
          "$ref": "#/definitions/blitter"
        },
        "bottom": {
          "description": "The area to draw at the bottom of the terminal (i.e. includes the player inventory).",
          "$ref": "#/definitions/blitter"
        },
        "maxRows": {
          "description": "If specified, limits the terminal to at most this many rows rather than using up available space.",
          "type": "integer",
          "minimum": 3
        },
        "slotsPerRow": {
          "description": "The number of slots per row on the background image.",
          "type": "integer",
          "minimum": 1
        },
        "sortable": {
          "description": "Defines if this terminal has a sort by button.",
          "type": "boolean",
          "default": true
        },
        "supportsAutoCrafting": {
          "description": "Defines if this terminal supports auto-crafting. If not, the button to show only craftable items is hidden.",
          "type": "boolean",
          "default": false
        },
        "stackSizeStyle": {
          "description": "The type of stack size rendering to use.",
          "type": "string",
          "default": "ITEMS",
          "enum": ["ITEMS", "FLUIDS"]
        },
        "showTooltipsWithItemInHand": {
          "type": "boolean",
          "default": false,
          "description": "Should the terminal show item tooltips for the network inventory even if the player has an item in their hand? Useful for showing fluid tooltips when the player has a bucket in hand."
        }
      }
    },
    "widgets": {
      "description": "Defines properties of various widgets that are positioned on the screen. The properties are widget-dependant. Which widget is placed is decided in code.",
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/definitions/position"
          },
          {
            "properties": {
              "width": {
                "type": "integer"
              },
              "height": {
                "type": "integer"
              },
              "hideEdge": {
                "description": "Used to hide the border around TabButtons",
                "type": "boolean"
              }
            }
          }
        ]
      }
    }
  }
}

=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/work_interval.json
{
  "$schema": "schema.json",
  "includes": ["common/common.json"],
  "background": {
    "texture": "guis/priority.png",
    "srcRect": [0, 0, 176, 125]
  },
  "text": {
    "dialog_title": {
      "text": {
        "translate": "gui.ae2.WorkInterval"
      },
      "position": {
        "left": 8,
        "top": 6
      }
    }
  },
  "widgets": {
    "back": {
      "left": 152,
      "top": -5,
      "width": 20,
      "height": 20
    },
    "workInterval": {
      "left": 20,
      "top": 30,
      "width": 138,
      "height": 62
    },
    "workIntervalInput": {
      "left": 56,
      "top": 55,
      "width": 65,
      "height": 12
    }
  }
}

=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/network_analyser.json
{
  "$schema": "schema.json",
  "includes": ["common/common.json"],
  "background": {
    "texture": "guis/network_analyser.png",
    "srcRect": [0, 0, 251, 168]
  },
  "widgets": {
    "mode_previous": {
      "left": 37,
      "top": 18,
      "width": 10,
      "height": 16
    },
    "mode_next": {
      "left": 105,
      "top": 18,
      "width": 10,
      "height": 16
    },
    "size_decrease": {
      "left": 37,
      "top": 46,
      "width": 10,
      "height": 16
    },
    "size_increase": {
      "left": 105,
      "top": 46,
      "width": 10,
      "height": 16
    },
    "reset_colors": {
      "left": 146,
      "top": 142,
      "width": 65,
      "height": 20
    },
    "color_0": {
      "left": 198,
      "top": 22,
      "width": 25,
      "height": 9
    },
    "color_1": {
      "left": 198,
      "top": 43,
      "width": 25,
      "height": 9
    },
    "color_2": {
      "left": 198,
      "top": 64,
      "width": 25,
      "height": 9
    },
    "color_3": {
      "left": 198,
      "top": 85,
      "width": 25,
      "height": 9
    },
    "color_4": {
      "left": 198,
      "top": 106,
      "width": 25,
      "height": 9
    },
    "color_5": {
      "left": 198,
      "top": 127,
      "width": 25,
      "height": 9
    },
    "color_window": {
      "left": 73,
      "top": 48,
      "width": 110,
      "height": 95
    },
    "color_red": {
      "left": 81,
      "top": 57,
      "width": 90,
      "height": 7
    },
    "color_green": {
      "left": 81,
      "top": 72,
      "width": 90,
      "height": 7
    },
    "color_blue": {
      "left": 81,
      "top": 87,
      "width": 90,
      "height": 7
    },
    "color_alpha": {
      "left": 81,
      "top": 102,
      "width": 90,
      "height": 7
    },
    "color_preview": {
      "left": 114,
      "top": 121,
      "width": 27,
      "height": 7
    },
    "color_apply": {
      "left": 88,
      "top": 117,
      "width": 16,
      "height": 16
    },
    "color_cancel": {
      "left": 150,
      "top": 117,
      "width": 16,
      "height": 16
    }
  },
  "text": {
    "mode_label": {
      "text": {
        "translate": "gui.ae2.network_analyser.mode"
      },
      "position": {
        "left": 24,
        "top": 22
      },
      "align": "CENTER"
    },
    "mode_value": {
      "position": {
        "left": 76,
        "top": 23
      },
      "align": "CENTER",
      "color": "WHITE"
    },
    "node_size_label": {
      "text": {
        "translate": "gui.ae2.network_analyser.node_size"
      },
      "position": {
        "left": 24,
        "top": 50
      },
      "align": "CENTER"
    },
    "node_size_value": {
      "position": {
        "left": 76,
        "top": 51
      },
      "align": "CENTER",
      "color": "WHITE"
    },
    "color_label_0": {
      "position": {
        "left": 134,
        "top": 23
      }
    },
    "color_label_1": {
      "position": {
        "left": 134,
        "top": 44
      }
    },
    "color_label_2": {
      "position": {
        "left": 134,
        "top": 65
      }
    },
    "color_label_3": {
      "position": {
        "left": 134,
        "top": 86
      }
    },
    "color_label_4": {
      "position": {
        "left": 134,
        "top": 107
      }
    },
    "color_label_5": {
      "position": {
        "left": 134,
        "top": 128
      }
    },
    "channel_mode": {
      "position": {
        "left": 16,
        "top": 72
      }
    },
    "normal_nodes": {
      "position": {
        "left": 16,
        "top": 86
      },
      "color": "ANALYSER_NORMAL_NODES"
    },
    "dense_nodes": {
      "position": {
        "left": 16,
        "top": 100
      },
      "color": "ANALYSER_DENSE_NODES"
    },
    "missing_nodes": {
      "position": {
        "left": 16,
        "top": 114
      },
      "color": "ANALYSER_MISSING_NODES"
    }
  }
}

=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/advanced_memory_card.json
{
  "$schema": "schema.json",
  "includes": ["common/common.json"],
  "text": {
    "dialog_title": {
      "position": {
        "left": 8,
        "top": 6
      },
      "text": {
        "translate": "gui.ae2.advanced_memory_card.title"
      }
    }
  },
  "widgets": {
    "verticalToolbar": {
      "left": 3,
      "top": 1
    },
    "search": {
      "left": 128,
      "top": 5,
      "width": 105,
      "height": 12
    },
    "entryList": {
      "left": 8,
      "top": 19,
      "width": 229,
      "height": 41
    },
    "emptyMessage": {
      "left": 32,
      "top": 22
    },
    "entryIcon": {
      "left": 3,
      "top": 3
    },
    "entryIoIcon": {
      "left": 0,
      "top": 4
    },
    "entryStatusIcon": {
      "left": 3,
      "top": 20
    },
    "entryName": {
      "left": 24,
      "top": 3
    },
    "entryType": {
      "left": 24,
      "top": 13
    },
    "entryFrequency": {
      "left": 24,
      "top": 23
    },
    "entryPosition": {
      "left": 24,
      "top": 33
    },
    "bindButton": {
      "left": 169,
      "top": 14,
      "width": 50,
      "height": 20
    },
    "scrollbar": {
      "left": 241,
      "top": 19,
      "height": 125
    }
  },
  "images": {
    "backgroundTop": {
      "texture": "guis/advanced_memory_card.png",
      "textureWidth": 256,
      "textureHeight": 256,
      "srcRect": [0, 0, 256, 60]
    },
    "backgroundRow": {
      "texture": "guis/advanced_memory_card.png",
      "textureWidth": 256,
      "textureHeight": 256,
      "srcRect": [0, 60, 256, 42]
    },
    "backgroundBottom": {
      "texture": "guis/advanced_memory_card.png",
      "textureWidth": 256,
      "textureHeight": 256,
      "srcRect": [0, 102, 256, 52]
    }
  }
}

=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/terminals/terminal_settings.json
{
  "$schema": "../schema.json",
  "includes": ["../common/common.json"],
  "generatedBackground": {
    "width": 200,
    "height": 216
  },
  "text": {
    "dialog_title": {
      "position": {
        "left": 8,
        "top": 7
      },
      "text": {
        "translate": "gui.ae2.TerminalSettingsTitle"
      }
    },
    "search_settings_title": {
      "position": {
        "left": 8,
        "top": 25
      },
      "text": {
        "translate": "gui.ae2.SearchSettingsTitle"
      }
    },
    "recursive_reserve_label": {
      "position": {
        "left": 10,
        "top": 130
      },
      "text": {
        "translate": "gui.ae2.TerminalSettingsRecursiveIngredientReserve"
      }
    },
    "player_pin_rows_label": {
      "position": {
        "left": 10,
        "top": 152
      },
      "text": {
        "translate": "gui.ae2.TerminalSettingsPlayerPinRows"
      }
    },
    "page_info": {
      "position": {
        "left": 86,
        "top": 194
      },
      "text": {
        "text": "1 / 2"
      }
    },
    "wireless_settings_title": {
      "position": {
        "left": 8,
        "top": 50
      },
      "text": {
        "translate": "gui.ae2.WirelessTerminalSettingsTitle"
      }
    }
  },
  "widgets": {
    "back": {
      "left": 176,
      "top": -5,
      "width": 20,
      "height": 20
    },
    "pinAutoCraftedItemsCheckbox": {
      "left": 10,
      "top": 25,
      "width": 180
    },
    "pinDisplaySortTopRadio": {
      "left": 10,
      "top": 45,
      "width": 85
    },
    "pinDisplayLockedGridRadio": {
      "left": 100,
      "top": 45,
      "width": 90
    },
    "notifyForFinishedCraftingJobsCheckbox": {
      "left": 10,
      "top": 65,
      "width": 180
    },
    "clearGridOnCloseCheckbox": {
      "left": 10,
      "top": 85,
      "width": 180
    },
    "autoFillPatternsCheckbox": {
      "left": 10,
      "top": 105,
      "width": 180
    },
    "recursiveReserveField": {
      "left": 154,
      "top": 127,
      "width": 36,
      "height": 12
    },
    "playerPinRowsField": {
      "left": 154,
      "top": 149,
      "width": 36,
      "height": 12
    },
    "pickBlockCheckbox": {
      "left": 10,
      "top": 25,
      "width": 180
    },
    "craftIfMissingCheckbox": {
      "left": 10,
      "top": 45,
      "width": 180
    },
    "restockCheckbox": {
      "left": 10,
      "top": 65,
      "width": 180
    },
    "magnetCheckbox": {
      "left": 10,
      "top": 85,
      "width": 85
    },
    "pickupToMECheckbox": {
      "left": 100,
      "top": 85,
      "width": 90
    },
    "magnetSettingsButton": {
      "left": 10,
      "top": 142,
      "width": 180,
      "height": 20
    },
    "useInternalSearchRadio": {
      "left": 10,
      "top": 45,
      "width": 75
    },
    "useExternalSearchRadio": {
      "left": 95,
      "top": 45,
      "width": 75
    },
    "rememberCheckbox": {
      "left": 10,
      "top": 67,
      "width": 150
    },
    "autoFocusCheckbox": {
      "left": 10,
      "top": 89,
      "width": 150
    },
    "syncWithExternalCheckbox": {
      "left": 10,
      "top": 111,
      "width": 150
    },
    "clearExternalCheckbox": {
      "left": 10,
      "top": 67,
      "width": 180
    },
    "previousPage": {
      "left": 10,
      "top": 190,
      "width": 22,
      "height": 20
    },
    "nextPage": {
      "left": 168,
      "top": 190,
      "width": 22,
      "height": 20
    }
  }
}

=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/renamer.json
{
  "$schema": "schema.json",
  "includes": ["common/common.json"],
  "background": {
    "texture": "guis/renamer.png",
    "srcRect": [0, 0, 176, 61]
  },
  "text": {
    "dialog_title": {
      "text": {
        "translate": "gui.ae2.Renamer"
      },
      "position": {
        "left": 12,
        "top": 8
      }
    }
  },
  "widgets": {
    "back": {
      "left": 152,
      "top": -5,
      "width": 20,
      "height": 20
    },
    "name": {
      "left": 9,
      "top": 33,
      "width": 158,
      "height": 12
    }
  }
}

=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/craft_confirm_cpu_list.json
{
  "$schema": "schema.json",
  "includes": ["common/common.json"],
  "background": {
    "texture": "guis/craft_confirm_cpu_list.png",
    "srcRect": [0, 0, 238, 194]
  },
  "text": {
    "dialog_title": {
      "position": {
        "left": 8,
        "top": 7
      }
    }
  },
  "widgets": {
    "search": {
      "left": 121,
      "top": 16,
      "width": 90,
      "height": 12
    },
    "scrollbar": {
      "left": 218,
      "top": 31,
      "width": 12
    },
    "sort": {
      "left": 8,
      "bottom": 25,
      "width": 16,
      "height": 16
    },
    "back": {
      "left": 214,
      "top": -5,
      "hideEdge": false,
      "width": 20,
      "height": 20
    },
    "verticalToolbar": {
      "left": 3,
      "top": 1
    }
  }
}
