=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://appliedenergistics.github.io/screen_style",
  "type": "object",
  "title": "AE2 Screen Style",
  "description": "Provides styling information for an AE2 UI screen",
  "required": [],
  "definitions": {
    "position": {
      "$comment": "Used to position an element in relationship to the size of the current dialog",
      "$id": "Position",
      "type": "object",
      "properties": {
        "left": {
          "type": "number",
          "description": "Positions the content to the right (positive) or left (negative) of the left screen edge."
        },
        "top": {
          "type": "number",
          "description": "Positions the content to the bottom (positive) or top (negative) of the top screen edge."
        },
        "right": {
          "type": "number",
          "description": "Positions the content to the left (positive) or right (negative) of the right screen edge."
        },
        "bottom": {
          "type": "number",
          "description": "Positions the content to the top (positive) or bottom (negative) of the bottom screen edge."
        }
      }
    },
    "color": {
      "$comment": "Definition of a color using a fake HTML notation",
      "type": "string",
      "pattern": "^#([0-9a-fA-F]{2}){3,4}$"
    },
    "text": {
      "$comment": "JSON schema definition of Minecraft text https://minecraft.wiki/w/Raw_JSON_text_format",
      "type": "object",
      "properties": {
        "extra": {
          "description": "Text that is displayed after this text, but that inherits this texts properties.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/text"
          }
        },
        "color": {
          "type": "string",
          "pattern": "^#([0-9a-fA-F]{6})$"
        },
        "font": {
          "type": "string",
          "default": "minecraft:default",
          "description": "Font in assets/<namespace>/font"
        },
        "bold": {
          "type": "boolean",
          "default": false
        },
        "italic": {
          "type": "boolean",
          "default": false
        },
        "underlined": {
          "type": "boolean",
          "default": false
        },
        "strikethrough": {
          "type": "boolean",
          "default": false
        },
        "obfuscated": {
          "type": "boolean",
          "default": false
        },
        "insertion": {
          "type": "string",
          "description": "When shift-clicked while the chat is open, the text of this property will be inserted."
        },
        "clickEvent": {
          "type": "object",
          "properties": {
            "action": {
              "type": "string",
              "enum": [
                "open_url",
                "open_file",
                "run_command",
                "suggest_command",
                "change_page",
                "copy_to_clipboard"
              ]
            },
            "value": {
              "type": "string"
            }
          },
          "required": ["action", "value"]
        },
        "hoverEvent": {
          "type": "object",
          "oneOf": [
            {
              "properties": {
                "action": {
                  "const": "show_text"
                },
                "contents": {
                  "$ref": "#/definitions/text"
                }
              }
            },
            {
              "properties": {
                "action": {
                  "const": "show_item"
                },
                "contents": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "default": "minecraft:air",
                      "description": "The item to show"
                    },
                    "count": {
                      "type": "integer",
                      "default": 1,
                      "description": "The item stack size"
                    },
                    "tag": {
                      "type": "string",
                      "description": "NBT of the item, serialized as string. See https://minecraft.wiki/w/Player.dat_format#Item_structure"
                    }
                  },
                  "required": ["id"]
                }
              }
            },
            {
              "properties": {
                "action": {
                  "const": "show_entity"
                },
                "contents": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "$ref": "#/definitions/text"
                    },
                    "type": {
                      "type": "string",
                      "default": "minecraft:pig",
                      "description": "The entity type id to show"
                    },
                    "id": {
                      "type": "string",
                      "description": "UUID of the entity to show"
                    }
                  }
                }
              }
            }
          ]
        }
      },
      "oneOf": [
        {
          "properties": {
            "text": {
              "description": "Display simple text",
              "type": "string"
            }
          },
          "required": ["text"]
        },
        {
          "properties": {
            "translate": {
              "description": "The ID of a translation key",
              "type": "string"
            },
            "with": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/text"
              }
            }
          },
          "required": ["translate"]
        },
        {
          "properties": {
            "keybind": {
              "type": "string",
              "description": "A keybind identifier"
            }
          },
          "required": ["keybind"]
        }
      ]
    },
    "rect": {
      "oneOf": [
        {
          "type": "array",
          "items": [
            {
              "type": "integer",
              "description": "x"
            },
            {
              "type": "integer",
              "description": "y"
            },
            {
              "type": "integer",
              "description": "width"
            },
            {
              "type": "integer",
              "description": "height"
            }
          ],
          "additionalItems": false
        },
        {
          "type": "object",
          "properties": {
            "x": {
              "type": "integer"
            },
            "y": {
              "type": "integer"
            },
            "width": {
              "type": "integer"
            },
            "height": {
              "type": "integer"
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "blitter": {
      "type": "object",
      "properties": {
        "texture": {
          "type": "string"
        },
        "textureWidth": {
          "type": "integer",
          "default": 256
        },
        "textureHeight": {
          "type": "integer",
          "default": 256
        },
        "srcRect": {
          "$ref": "#/definitions/rect"
        }
      },
      "required": ["texture"]
    },
    "generatedBackground": {
      "type": "object",
      "properties": {
        "width": {
          "type": "integer"
        },
        "height": {
          "type": "integer"
        }
      },
      "required": ["width", "height"]
    }
  },
  "properties": {
    "includes": {
      "description": "Relative path to other files to include before processing this one.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "palette": {
      "$comment": "See PaletteColor enum",
      "type": "object",
      "description": "Defines colors used through the UI screen",
      "properties": {
        "DEFAULT_TEXT_COLOR": {
          "$ref": "#/definitions/color"
        },
        "MUTED_TEXT_COLOR": {
          "$ref": "#/definitions/color"
        },
        "SELECTION_COLOR": {
          "$ref": "#/definitions/color"
        },
        "TEXTFIELD_PLACEHOLDER": {
          "$ref": "#/definitions/color"
        },
        "TEXTFIELD_SELECTION": {
          "$ref": "#/definitions/color"
        },
        "TEXTFIELD_ERROR": {
          "$ref": "#/definitions/color"
        },
        "TEXTFIELD_TEXT": {
          "$ref": "#/definitions/color"
        },
        "ERROR": {
          "$ref": "#/definitions/color"
        },
        "WHITE": {
          "$ref": "#/definitions/color"
        },
        "ANALYSER_NORMAL_NODES": {
          "$ref": "#/definitions/color"
        },
        "ANALYSER_DENSE_NODES": {
          "$ref": "#/definitions/color"
        },
        "ANALYSER_MISSING_NODES": {
          "$ref": "#/definitions/color"
        }
      }
    },
    "background": {
      "$ref": "#/definitions/blitter"
    },
    "generatedBackground": {
      "$ref": "#/definitions/generatedBackground"
    },
    "slots": {
      "type": "object",
      "description": "Defines positions for slots and their grid alignment",
      "additionalProperties": {
        "type": "object",
        "allOf": [
          {
            "properties": {
              "grid": {
                "$comment": "Configures the slots with this semantic in a grid",
                "enum": [
                  "IO_BUS_CONFIG",
                  "BREAK_AFTER_9COLS",
                  "BREAK_AFTER_2COLS",
                  "BREAK_AFTER_3COLS",
                  "HORIZONTAL",
                  "VERTICAL"
                ]
              }
            }
          },
          {
            "$ref": "#/definitions/position"
          }
        ]
      },
      "propertyNames": {
        "$comment": "List SlotSemantic names here",
        "enum": [
          "NONE",
          "STORAGE",
          "PLAYER_INVENTORY",
          "PLAYER_HOTBAR",
          "TOOLBOX",
          "CONFIG",
          "UPGRADE",
          "STORAGE_CELL",
          "INSCRIBER_PLATE_TOP",
          "INSCRIBER_PLATE_BOTTOM",
          "MACHINE_INPUT",
          "MACHINE_PROCESSING",
          "MACHINE_OUTPUT",
          "MACHINE_CRAFTING_GRID",
          "CANER_CONTENT",
          "CANER_CONTAINER",
          "BLANK_PATTERN",
          "ENCODED_PATTERN",
          "PATTERN_MODIFIER_PANEL",
          "PATTERN_MODIFIER_TARGET",
          "PATTERN_MODIFIER_CLONE",
          "PATTERN_MODIFIER_BLANKS",
          "PATTERN_MODIFIER_REPLACE_TARGET",
          "PATTERN_MODIFIER_REPLACE_WITH",
          "VIEW_CELL",
          "MAGNET_PICKUP_CONFIG",
          "MAGNET_INSERT_CONFIG",
          "WIRELESS_SINGULARITY",
          "CRAFTING_GRID",
          "CRAFTING_RESULT",
          "PROCESSING_INPUTS",
          "PROCESSING_OUTPUTS",
          "MISSING_INGREDIENT"
        ]
      }
    },
    "text": {
      "description": "Defines text that will be shown on the UI, the property name is used to reference text from code",
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "text": {
            "$ref": "#/definitions/text"
          },
          "color": {
            "$comment": "See enum PaletteColor",
            "enum": [
              "DEFAULT_TEXT_COLOR",
              "MUTED_TEXT_COLOR",
              "SELECTION_COLOR",
              "ERROR",
              "WHITE",
              "ANALYSER_NORMAL_NODES",
              "ANALYSER_DENSE_NODES",
              "ANALYSER_MISSING_NODES"
            ],
            "default": "DEFAULT_TEXT_COLOR"
          },
          "position": {
            "$ref": "#/definitions/position"
          },
          "scale": {
            "type": "number",
            "default": 1,
            "minimum": 0.1,
            "maximum": 4,
            "$comment": "Can be used to display smaller text, 0.5 works well, usually"
          },
          "align": {
            "type": "string",
            "default": "LEFT",
            "enum": ["LEFT", "CENTER", "RIGHT"]
          },
          "maxWidth": {
            "type": "number",
            "minimum": 0,
            "default": 0,
            "description": "If greater than 0, the text will be word-wrapped when it reaches the given width in pixels."
          }
        }
      }
    },
    "tooltips": {
      "description": "Defines areas that will show a tooltip on the screen. These areas are evaluated after everything else that could show a tooltip.",
      "type": "object",
      "additionalProperties": {
        "allOf": [
          {
            "type": "object",
            "properties": {
              "tooltip": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/text"
                }
              },
              "width": {
                "type": "integer"
              },
              "height": {
                "type": "integer"
              }
            },
            "required": ["tooltip", "width", "height"]
          },
          {
            "$ref": "#/definitions/position"
          }
        ]
      }
    },
    "images": {
      "description": "Additional screen-specific images",
      "additionalProperties": {
        "$ref": "#/definitions/blitter"
      }
    },
    "terminalStyle": {
      "description": "If this screen is a terminal, this defines required properties to display it properly",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "header": {
          "description": "The top of the terminal background right up to the first row of content.",
          "$ref": "#/definitions/blitter"
        },
        "firstRow": {
          "description": "The area to draw for the first row in the terminal. Usually this includes the top of the scrollbar.",
          "$ref": "#/definitions/blitter"
        },
        "row": {
          "description": "The area to repeat for every row in the terminal. Should be 16px for the item + 2px for the border in size.",
          "$ref": "#/definitions/blitter"
        },
        "lastRow": {
          "description": "The area to draw for the last row in the terminal. Usually this includes the top of the scrollbar.",
          "$ref": "#/definitions/blitter"
        },
        "bottom": {
          "description": "The area to draw at the bottom of the terminal (i.e. includes the player inventory).",
          "$ref": "#/definitions/blitter"
        },
        "maxRows": {
          "description": "If specified, limits the terminal to at most this many rows rather than using up available space.",
          "type": "integer",
          "minimum": 3
        },
        "slotsPerRow": {
          "description": "The number of slots per row on the background image.",
          "type": "integer",
          "minimum": 1
        },
        "sortable": {
          "description": "Defines if this terminal has a sort by button.",
          "type": "boolean",
          "default": true
        },
        "supportsAutoCrafting": {
          "description": "Defines if this terminal supports auto-crafting. If not, the button to show only craftable items is hidden.",
          "type": "boolean",
          "default": false
        },
        "stackSizeStyle": {
          "description": "The type of stack size rendering to use.",
          "type": "string",
          "default": "ITEMS",
          "enum": ["ITEMS", "FLUIDS"]
        },
        "showTooltipsWithItemInHand": {
          "type": "boolean",
          "default": false,
          "description": "Should the terminal show item tooltips for the network inventory even if the player has an item in their hand? Useful for showing fluid tooltips when the player has a bucket in hand."
        }
      }
    },
    "widgets": {
      "description": "Defines properties of various widgets that are positioned on the screen. The properties are widget-dependant. Which widget is placed is decided in code.",
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/definitions/position"
          },
          {
            "properties": {
              "width": {
                "type": "integer"
              },
              "height": {
                "type": "integer"
              },
              "hideEdge": {
                "description": "Used to hide the border around TabButtons",
                "type": "boolean"
              }
            }
          }
        ]
      }
    }
  }
}

=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/od_export_bus.json
{
  "$schema": "schema.json",
  "includes": [
    "common/common.json",
    "common/player_inventory.json",
    "common/toolbox.json"
  ],
  "background": {
    "texture": "guis/od_storage_bus.png",
    "srcRect": [
      0,
      0,
      176,
      209
    ]
  },
  "text": {
    "dialog_title": {
      "text": {
        "translate": "gui.ae2.ODExportBus"
      },
      "position": {
        "left": 8,
        "top": 6
      }
    },
    "whitelist": {
      "text": {
        "translate": "gui.ae2.ODFilterWhite"
      },
      "position": {
        "left": 8,
        "top": 40
      },
      "align": "LEFT"
    },
    "blacklist": {
      "text": {
        "translate": "gui.ae2.ODFilterBlack"
      },
      "position": {
        "right": 8,
        "top": 56
      },
      "align": "RIGHT"
    },
    "tooltip_left": {
      "text": {
        "translate": "gui.ae2.ODFilterDesc1"
      },
      "position": {
        "left": 8,
        "top": 94
      },
      "align": "LEFT"
    },
    "tooltip_right": {
      "text": {
        "translate": "gui.ae2.ODFilterDesc2"
      },
      "position": {
        "right": 8,
        "top": 94
      },
      "align": "RIGHT"
    },
    "tooltip_bottom": {
      "text": {
        "translate": "gui.ae2.ODFilterDesc3"
      },
      "position": {
        "left": 8,
        "top": 104
      },
      "align": "LEFT"
    }
  },
  "widgets": {
    "whiteExpression": {
      "left": 8,
      "top": 26,
      "width": 160,
      "height": 26
    },
    "blackExpression": {
      "left": 8,
      "top": 66,
      "width": 160,
      "height": 26
    },
    "openPriority": {
      "left": 152,
      "top": -5,
      "width": 20,
      "height": 20
    }
  }
}

=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/output_sides.json
{
  "$schema": "schema.json",
  "includes": ["common/common.json"],
  "background": {
    "texture": "guis/priority.png",
    "srcRect": [0, 0, 176, 125]
  },
  "text": {
    "dialog_title": {
      "text": {
        "translate": "gui.ae2.OutputSides"
      },
      "position": {
        "left": 8,
        "top": 6
      }
    }
  },
  "widgets": {
    "returnToParent": {
      "left": 152,
      "top": -5,
      "width": 20,
      "height": 20
    },
    "clear": {
      "left": 128,
      "top": -5,
      "width": 20,
      "height": 20
    },
    "side_top": {
      "left": 80,
      "top": 26,
      "width": 16,
      "height": 16
    },
    "side_left": {
      "left": 54,
      "top": 50,
      "width": 16,
      "height": 16
    },
    "side_front": {
      "left": 80,
      "top": 50,
      "width": 16,
      "height": 16
    },
    "side_right": {
      "left": 106,
      "top": 50,
      "width": 16,
      "height": 16
    },
    "side_bottom": {
      "left": 80,
      "top": 74,
      "width": 16,
      "height": 16
    },
    "side_back": {
      "left": 80,
      "top": 98,
      "width": 16,
      "height": 16
    }
  }
}

=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/crafting_status.json
{
  "$schema": "schema.json",
  "includes": ["common/common.json"],
  "background": {
    "texture": "guis/craftingcpu.png",
    "srcRect": [0, 0, 238, 185]
  },
  "text": {
    "dialog_title": {
      "position": {
        "left": 8,
        "top": 7
      }
    },
    "cpuListTitle": {
      "position": {
        "top": 7,
        "left": -81
      },
      "text": {
        "translate": "gui.ae2.CraftingCPUs"
      }
    }
  },
  "widgets": {
    "search": {
      "left": 130,
      "top": 5,
      "width": 83,
      "height": 12
    },
    "suspend": {
      "left": 103,
      "bottom": 25,
      "width": 50,
      "height": 20
    },
    "cancel": {
      "left": 163,
      "bottom": 25,
      "width": 50,
      "height": 20
    },
    "scrollbar": {
      "left": 218,
      "top": 19,
      "width": 12
    },
    "back": {
      "left": 214,
      "top": -5,
      "hideEdge": false,
      "width": 20,
      "height": 20
    },
    "selectCpuList": {
      "left": -88,
      "top": 0,
      "width": 94
    },
    "selectCpuScrollbar": {
      "left": -11,
      "top": 19,
      "width": 12
    },
    "verticalToolbar": {
      "left": 0,
      "top": 0
    },
    "terminalStyle": {
      "left": -22,
      "bottom": 24,
      "width": 20,
      "height": 20
    }
  },
  "images": {
    "cpuList": {
      "texture": "guis/cpu_selector.png",
      "textureWidth": 256,
      "textureHeight": 256,
      "srcRect": [0, 0, 94, 164]
    },
    "cpuListButton": {
      "texture": "guis/cpu_selector.png",
      "textureWidth": 256,
      "textureHeight": 256,
      "srcRect": [100, 0, 67, 22]
    },
    "cpuListButtonSelected": {
      "texture": "guis/cpu_selector.png",
      "textureWidth": 256,
      "textureHeight": 256,
      "srcRect": [100, 22, 67, 22]
    }
  }
}

=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/terminals/pattern_encoding_access_terminal.json
{
	"$schema": "../schema.json",
	"includes": [
		"../common/common.json",
		"../common/player_inventory.json",
		"accessencoding/crafting.json",
		"accessencoding/processing.json"
	],
	"text": {
		"crafting_grid_title": {
			"text": {
				"translate": "gui.ae2.PatternEncoding"
			},
			"position": {
				"left": 17,
				"bottom": 176
			}
		}
	},
	"widgets": {
		"scrollbar": {
			"left": 193,
			"top": 31
		},
		"search": {
			"left": 16,
			"top": 17,
			"width": 65,
			"height": 10
		},
		"inputSearch": {
			"left": 113,
			"top": 4,
			"width": 65,
			"height": 10
		},
		"outputSearch": {
			"left": 113,
			"top": 17,
			"width": 65,
			"height": 10
		},
		"patternModifierPanel": {
			"left": -126,
			"top": 59,
			"width": 86,
			"height": 180
		},
		"patternModifierPanelAmount0": {
			"left": -63,
			"top": 67,
			"width": 18,
			"height": 20
		},
		"patternModifierPanelAmount1": {
			"left": -63,
			"top": 89,
			"width": 18,
			"height": 20
		},
		"patternModifierPanelAmount2": {
			"left": -63,
			"top": 111,
			"width": 18,
			"height": 20
		},
		"patternModifierPanelAmount3": {
			"left": -63,
			"top": 133,
			"width": 18,
			"height": 20
		},
		"patternModifierPanelAmount4": {
			"left": -63,
			"top": 155,
			"width": 18,
			"height": 20
		},
		"patternModifierPanelAmount5": {
			"left": -63,
			"top": 177,
			"width": 18,
			"height": 20
		},
		"patternModifierPanelClear": {
			"left": -63,
			"top": 199,
			"width": 18,
			"height": 20
		},
		"modeTabButton0": {
			"left": 191,
			"bottom": 174,
			"width": 22,
			"height": 22
		},
		"modeTabButton1": {
			"left": 191,
			"bottom": 153,
			"width": 22,
			"height": 22
		},
		"modePanel0": {
			"left": 18,
			"bottom": 166
		},
		"modePanel1": {
			"left": 18,
			"bottom": 166
		},
		"encodePattern": {
			"left": 156,
			"bottom": 145
		},
		"uploadPattern": {
			"left": 174,
			"bottom": 140,
			"width": 8,
			"height": 8
		}
	},
	"slots": {
		"PLAYER_INVENTORY": {
			"left": 17,
			"bottom": 84,
			"grid": "BREAK_AFTER_9COLS"
		},
		"PLAYER_HOTBAR": {
			"left": 17,
			"bottom": 26,
			"grid": "HORIZONTAL"
		},
		"BLANK_PATTERN": {
			"left": 156,
			"bottom": 165
		},
		"ENCODED_PATTERN": {
			"left": 156,
			"bottom": 118
		}
	}
}

=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/pattern_provider.json
{
  "$schema": "schema.json",
  "includes": ["common/common.json", "common/player_inventory.json", "common/toolbox.json"],
  "background": {
    "texture": "guis/pattern_provider.png",
    "srcRect": [0, 0, 176, 215]
  },
  "slots": {
    "ENCODED_PATTERN": {
      "left": 8,
      "top": 45,
      "grid": "HORIZONTAL"
    },
    "STORAGE": {
      "left": 8,
      "top": 97,
      "grid": "HORIZONTAL"
    }
  },
  "text": {
    "dialog_title": {
      "text": {
        "translate": "gui.ae2.CraftingInterface"
      },
      "position": {
        "left": 8,
        "top": 6
      }
    },
    "interface_config": {
      "text": {
        "translate": "gui.ae2.Patterns"
      },
      "position": {
        "left": 8,
        "top": 34
      }
    },
    "interface_stored_items": {
      "text": {
        "translate": "gui.ae2.ReturnInventory"
      },
      "position": {
        "left": 8,
        "top": 86
      }
    }
  },
  "widgets": {
    "openPriority": {
      "left": 152,
      "top": -5,
      "width": 20,
      "height": 20
    },
    "lockReason": {
      "left": 5,
      "top": 15
    }
  }
}

=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/crafting_cpu.json
{
  "$schema": "schema.json",
  "includes": ["common/common.json"],
  "background": {
    "texture": "guis/craftingcpu.png",
    "srcRect": [0, 0, 238, 185]
  },
  "text": {
    "dialog_title": {
      "position": {
        "left": 8,
        "top": 7
      }
    }
  },
  "widgets": {
    "search": {
      "left": 130,
      "top": 5,
      "width": 83,
      "height": 12
    },
    "suspend": {
      "left": 103,
      "bottom": 25,
      "width": 50,
      "height": 20
    },
    "cancel": {
      "left": 163,
      "bottom": 25,
      "width": 50,
      "height": 20
    },
    "scrollbar": {
      "left": 218,
      "top": 19,
      "width": 12
    },
    "verticalToolbar": {
      "left": 3,
      "top": 1
    }
  }
}

=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/terminals/pattern_encoding_terminal.json
{
  "$schema": "../schema.json",
  "includes": [
    "terminal.json",
    "encoding/crafting.json",
    "encoding/processing.json"
  ],
  "slots": {
    "BLANK_PATTERN": {
      "left": 147,
      "bottom": 165
    },
    "ENCODED_PATTERN": {
      "left": 147,
      "bottom": 118
    }
  },
  "text": {
    "dialog_title": {
      "text": {
        "translate": "gui.ae2.Terminal"
      },
      "position": {
        "left": 8,
        "top": 6
      }
    },
    "crafting_grid_title": {
      "text": {
        "translate": "gui.ae2.PatternEncoding"
      },
      "position": {
        "left": 8,
        "bottom": 177
      }
    }
  },
  "terminalStyle": {
    "header": {
      "texture": "guis/pattern.png",
      "srcRect": [0, 0, 195, 17]
    },
    "firstRow": {
      "texture": "guis/pattern.png",
      "srcRect": [0, 17, 195, 18]
    },
    "row": {
      "texture": "guis/pattern.png",
      "srcRect": [0, 35, 195, 18]
    },
    "lastRow": {
      "texture": "guis/pattern.png",
      "srcRect": [0, 53, 195, 18]
    },
    "bottom": {
      "texture": "guis/pattern.png",
      "srcRect": [0, 71, 195, 180]
    }
  },
  "widgets": {
    "modeTabButton0": {
      "left": 173,
      "bottom": 174,
      "width": 22,
      "height": 22
    },
    "modeTabButton1": {
      "left": 173,
      "bottom": 153,
      "width": 22,
      "height": 22
    },
    "modePanel0": {
      "left": 9,
      "bottom": 166
    },
    "modePanel1": {
      "left": 9,
      "bottom": 166
    },
    "encodePattern": {
      "left": 147,
      "bottom": 145
    },
    "uploadPattern": {
      "left": 165,
      "bottom": 140,
      "width": 8,
      "height": 8
    },
    "providerSelectOverlay": {
      "left": 0,
      "top": 0,
      "width": 0,
      "height": 0
    },
    "patternModifierPanel": {
      "left": -126,
      "top": 59,
      "width": 86,
      "height": 180
    },
    "patternModifierPanelAmount0": {
      "left": -63,
      "top": 67,
      "width": 18,
      "height": 20
    },
    "patternModifierPanelAmount1": {
      "left": -63,
      "top": 89,
      "width": 18,
      "height": 20
    },
    "patternModifierPanelAmount2": {
      "left": -63,
      "top": 111,
      "width": 18,
      "height": 20
    },
    "patternModifierPanelAmount3": {
      "left": -63,
      "top": 133,
      "width": 18,
      "height": 20
    },
    "patternModifierPanelAmount4": {
      "left": -63,
      "top": 155,
      "width": 18,
      "height": 20
    },
    "patternModifierPanelAmount5": {
      "left": -63,
      "top": 177,
      "width": 18,
      "height": 20
    },
    "patternModifierPanelClear": {
      "left": -63,
      "top": 199,
      "width": 18,
      "height": 20
    }
  }
}
