=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://appliedenergistics.github.io/screen_style",
  "type": "object",
  "title": "AE2 Screen Style",
  "description": "Provides styling information for an AE2 UI screen",
  "required": [],
  "definitions": {
    "position": {
      "$comment": "Used to position an element in relationship to the size of the current dialog",
      "$id": "Position",
      "type": "object",
      "properties": {
        "left": {
          "type": "number",
          "description": "Positions the content to the right (positive) or left (negative) of the left screen edge."
        },
        "top": {
          "type": "number",
          "description": "Positions the content to the bottom (positive) or top (negative) of the top screen edge."
        },
        "right": {
          "type": "number",
          "description": "Positions the content to the left (positive) or right (negative) of the right screen edge."
        },
        "bottom": {
          "type": "number",
          "description": "Positions the content to the top (positive) or bottom (negative) of the bottom screen edge."
        }
      }
    },
    "color": {
      "$comment": "Definition of a color using a fake HTML notation",
      "type": "string",
      "pattern": "^#([0-9a-fA-F]{2}){3,4}$"
    },
    "text": {
      "$comment": "JSON schema definition of Minecraft text https://minecraft.wiki/w/Raw_JSON_text_format",
      "type": "object",
      "properties": {
        "extra": {
          "description": "Text that is displayed after this text, but that inherits this texts properties.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/text"
          }
        },
        "color": {
          "type": "string",
          "pattern": "^#([0-9a-fA-F]{6})$"
        },
        "font": {
          "type": "string",
          "default": "minecraft:default",
          "description": "Font in assets/<namespace>/font"
        },
        "bold": {
          "type": "boolean",
          "default": false
        },
        "italic": {
          "type": "boolean",
          "default": false
        },
        "underlined": {
          "type": "boolean",
          "default": false
        },
        "strikethrough": {
          "type": "boolean",
          "default": false
        },
        "obfuscated": {
          "type": "boolean",
          "default": false
        },
        "insertion": {
          "type": "string",
          "description": "When shift-clicked while the chat is open, the text of this property will be inserted."
        },
        "clickEvent": {
          "type": "object",
          "properties": {
            "action": {
              "type": "string",
              "enum": [
                "open_url",
                "open_file",
                "run_command",
                "suggest_command",
                "change_page",
                "copy_to_clipboard"
              ]
            },
            "value": {
              "type": "string"
            }
          },
          "required": ["action", "value"]
        },
        "hoverEvent": {
          "type": "object",
          "oneOf": [
            {
              "properties": {
                "action": {
                  "const": "show_text"
                },
                "contents": {
                  "$ref": "#/definitions/text"
                }
              }
            },
            {
              "properties": {
                "action": {
                  "const": "show_item"
                },
                "contents": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "default": "minecraft:air",
                      "description": "The item to show"
                    },
                    "count": {
                      "type": "integer",
                      "default": 1,
                      "description": "The item stack size"
                    },
                    "tag": {
                      "type": "string",
                      "description": "NBT of the item, serialized as string. See https://minecraft.wiki/w/Player.dat_format#Item_structure"
                    }
                  },
                  "required": ["id"]
                }
              }
            },
            {
              "properties": {
                "action": {
                  "const": "show_entity"
                },
                "contents": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "$ref": "#/definitions/text"
                    },
                    "type": {
                      "type": "string",
                      "default": "minecraft:pig",
                      "description": "The entity type id to show"
                    },
                    "id": {
                      "type": "string",
                      "description": "UUID of the entity to show"
                    }
                  }
                }
              }
            }
          ]
        }
      },
      "oneOf": [
        {
          "properties": {
            "text": {
              "description": "Display simple text",
              "type": "string"
            }
          },
          "required": ["text"]
        },
        {
          "properties": {
            "translate": {
              "description": "The ID of a translation key",
              "type": "string"
            },
            "with": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/text"
              }
            }
          },
          "required": ["translate"]
        },
        {
          "properties": {
            "keybind": {
              "type": "string",
              "description": "A keybind identifier"
            }
          },
          "required": ["keybind"]
        }
      ]
    },
    "rect": {
      "oneOf": [
        {
          "type": "array",
          "items": [
            {
              "type": "integer",
              "description": "x"
            },
            {
              "type": "integer",
              "description": "y"
            },
            {
              "type": "integer",
              "description": "width"
            },
            {
              "type": "integer",
              "description": "height"
            }
          ],
          "additionalItems": false
        },
        {
          "type": "object",
          "properties": {
            "x": {
              "type": "integer"
            },
            "y": {
              "type": "integer"
            },
            "width": {
              "type": "integer"
            },
            "height": {
              "type": "integer"
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "blitter": {
      "type": "object",
      "properties": {
        "texture": {
          "type": "string"
        },
        "textureWidth": {
          "type": "integer",
          "default": 256
        },
        "textureHeight": {
          "type": "integer",
          "default": 256
        },
        "srcRect": {
          "$ref": "#/definitions/rect"
        }
      },
      "required": ["texture"]
    },
    "generatedBackground": {
      "type": "object",
      "properties": {
        "width": {
          "type": "integer"
        },
        "height": {
          "type": "integer"
        }
      },
      "required": ["width", "height"]
    }
  },
  "properties": {
    "includes": {
      "description": "Relative path to other files to include before processing this one.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "palette": {
      "$comment": "See PaletteColor enum",
      "type": "object",
      "description": "Defines colors used through the UI screen",
      "properties": {
        "DEFAULT_TEXT_COLOR": {
          "$ref": "#/definitions/color"
        },
        "MUTED_TEXT_COLOR": {
          "$ref": "#/definitions/color"
        },
        "SELECTION_COLOR": {
          "$ref": "#/definitions/color"
        },
        "TEXTFIELD_PLACEHOLDER": {
          "$ref": "#/definitions/color"
        },
        "TEXTFIELD_SELECTION": {
          "$ref": "#/definitions/color"
        },
        "TEXTFIELD_ERROR": {
          "$ref": "#/definitions/color"
        },
        "TEXTFIELD_TEXT": {
          "$ref": "#/definitions/color"
        },
        "ERROR": {
          "$ref": "#/definitions/color"
        },
        "WHITE": {
          "$ref": "#/definitions/color"
        },
        "ANALYSER_NORMAL_NODES": {
          "$ref": "#/definitions/color"
        },
        "ANALYSER_DENSE_NODES": {
          "$ref": "#/definitions/color"
        },
        "ANALYSER_MISSING_NODES": {
          "$ref": "#/definitions/color"
        }
      }
    },
    "background": {
      "$ref": "#/definitions/blitter"
    },
    "generatedBackground": {
      "$ref": "#/definitions/generatedBackground"
    },
    "slots": {
      "type": "object",
      "description": "Defines positions for slots and their grid alignment",
      "additionalProperties": {
        "type": "object",
        "allOf": [
          {
            "properties": {
              "grid": {
                "$comment": "Configures the slots with this semantic in a grid",
                "enum": [
                  "IO_BUS_CONFIG",
                  "BREAK_AFTER_9COLS",
                  "BREAK_AFTER_2COLS",
                  "BREAK_AFTER_3COLS",
                  "HORIZONTAL",
                  "VERTICAL"
                ]
              }
            }
          },
          {
            "$ref": "#/definitions/position"
          }
        ]
      },
      "propertyNames": {
        "$comment": "List SlotSemantic names here",
        "enum": [
          "NONE",
          "STORAGE",
          "PLAYER_INVENTORY",
          "PLAYER_HOTBAR",
          "TOOLBOX",
          "CONFIG",
          "UPGRADE",
          "STORAGE_CELL",
          "INSCRIBER_PLATE_TOP",
          "INSCRIBER_PLATE_BOTTOM",
          "MACHINE_INPUT",
          "MACHINE_PROCESSING",
          "MACHINE_OUTPUT",
          "MACHINE_CRAFTING_GRID",
          "CANER_CONTENT",
          "CANER_CONTAINER",
          "BLANK_PATTERN",
          "ENCODED_PATTERN",
          "PATTERN_MODIFIER_PANEL",
          "PATTERN_MODIFIER_TARGET",
          "PATTERN_MODIFIER_CLONE",
          "PATTERN_MODIFIER_BLANKS",
          "PATTERN_MODIFIER_REPLACE_TARGET",
          "PATTERN_MODIFIER_REPLACE_WITH",
          "VIEW_CELL",
          "MAGNET_PICKUP_CONFIG",
          "MAGNET_INSERT_CONFIG",
          "WIRELESS_SINGULARITY",
          "CRAFTING_GRID",
          "CRAFTING_RESULT",
          "PROCESSING_INPUTS",
          "PROCESSING_OUTPUTS",
          "MISSING_INGREDIENT"
        ]
      }
    },
    "text": {
      "description": "Defines text that will be shown on the UI, the property name is used to reference text from code",
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "text": {
            "$ref": "#/definitions/text"
          },
          "color": {
            "$comment": "See enum PaletteColor",
            "enum": [
              "DEFAULT_TEXT_COLOR",
              "MUTED_TEXT_COLOR",
              "SELECTION_COLOR",
              "ERROR",
              "WHITE",
              "ANALYSER_NORMAL_NODES",
              "ANALYSER_DENSE_NODES",
              "ANALYSER_MISSING_NODES"
            ],
            "default": "DEFAULT_TEXT_COLOR"
          },
          "position": {
            "$ref": "#/definitions/position"
          },
          "scale": {
            "type": "number",
            "default": 1,
            "minimum": 0.1,
            "maximum": 4,
            "$comment": "Can be used to display smaller text, 0.5 works well, usually"
          },
          "align": {
            "type": "string",
            "default": "LEFT",
            "enum": ["LEFT", "CENTER", "RIGHT"]
          },
          "maxWidth": {
            "type": "number",
            "minimum": 0,
            "default": 0,
            "description": "If greater than 0, the text will be word-wrapped when it reaches the given width in pixels."
          }
        }
      }
    },
    "tooltips": {
      "description": "Defines areas that will show a tooltip on the screen. These areas are evaluated after everything else that could show a tooltip.",
      "type": "object",
      "additionalProperties": {
        "allOf": [
          {
            "type": "object",
            "properties": {
              "tooltip": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/text"
                }
              },
              "width": {
                "type": "integer"
              },
              "height": {
                "type": "integer"
              }
            },
            "required": ["tooltip", "width", "height"]
          },
          {
            "$ref": "#/definitions/position"
          }
        ]
      }
    },
    "images": {
      "description": "Additional screen-specific images",
      "additionalProperties": {
        "$ref": "#/definitions/blitter"
      }
    },
    "terminalStyle": {
      "description": "If this screen is a terminal, this defines required properties to display it properly",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "header": {
          "description": "The top of the terminal background right up to the first row of content.",
          "$ref": "#/definitions/blitter"
        },
        "firstRow": {
          "description": "The area to draw for the first row in the terminal. Usually this includes the top of the scrollbar.",
          "$ref": "#/definitions/blitter"
        },
        "row": {
          "description": "The area to repeat for every row in the terminal. Should be 16px for the item + 2px for the border in size.",
          "$ref": "#/definitions/blitter"
        },
        "lastRow": {
          "description": "The area to draw for the last row in the terminal. Usually this includes the top of the scrollbar.",
          "$ref": "#/definitions/blitter"
        },
        "bottom": {
          "description": "The area to draw at the bottom of the terminal (i.e. includes the player inventory).",
          "$ref": "#/definitions/blitter"
        },
        "maxRows": {
          "description": "If specified, limits the terminal to at most this many rows rather than using up available space.",
          "type": "integer",
          "minimum": 3
        },
        "slotsPerRow": {
          "description": "The number of slots per row on the background image.",
          "type": "integer",
          "minimum": 1
        },
        "sortable": {
          "description": "Defines if this terminal has a sort by button.",
          "type": "boolean",
          "default": true
        },
        "supportsAutoCrafting": {
          "description": "Defines if this terminal supports auto-crafting. If not, the button to show only craftable items is hidden.",
          "type": "boolean",
          "default": false
        },
        "stackSizeStyle": {
          "description": "The type of stack size rendering to use.",
          "type": "string",
          "default": "ITEMS",
          "enum": ["ITEMS", "FLUIDS"]
        },
        "showTooltipsWithItemInHand": {
          "type": "boolean",
          "default": false,
          "description": "Should the terminal show item tooltips for the network inventory even if the player has an item in their hand? Useful for showing fluid tooltips when the player has a bucket in hand."
        }
      }
    },
    "widgets": {
      "description": "Defines properties of various widgets that are positioned on the screen. The properties are widget-dependant. Which widget is placed is decided in code.",
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/definitions/position"
          },
          {
            "properties": {
              "width": {
                "type": "integer"
              },
              "height": {
                "type": "integer"
              },
              "hideEdge": {
                "description": "Used to hide the border around TabButtons",
                "type": "boolean"
              }
            }
          }
        ]
      }
    }
  }
}

=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/threshold_level_emitter.json
{
  "$schema": "schema.json",
  "includes": [
    "common/common.json",
    "common/player_inventory.json",
    "common/toolbox.json"
  ],
  "background": {
    "texture": "guis/threshold_level_emitter.png",
    "srcRect": [0, 0, 176, 186]
  },
  "slots": {
    "CONFIG": {
      "left": 137,
      "top": 47
    }
  },
  "text": {
    "dialog_title": {
      "text": {
        "translate": "gui.ae2.ThresholdLevelEmitter"
      },
      "position": {
        "left": 8,
        "top": 6
      }
    },
    "upper_text": {
      "text": {
        "translate": "gui.ae2.ThresholdLevelEmitterUpper"
      },
      "position": {
        "left": 20,
        "top": 23
      }
    },
    "lower_text": {
      "text": {
        "translate": "gui.ae2.ThresholdLevelEmitterLower"
      },
      "position": {
        "left": 20,
        "top": 58
      }
    }
  },
  "widgets": {
    "upperLevel": {
      "left": 20,
      "top": 34,
      "width": 83,
      "height": 12
    },
    "upperLevelInput": {
      "left": 20,
      "top": 34,
      "width": 83,
      "height": 12
    },
    "lowerLevel": {
      "left": 20,
      "top": 69,
      "width": 83,
      "height": 12
    },
    "lowerLevelInput": {
      "left": 20,
      "top": 69,
      "width": 83,
      "height": 12
    }
  }
}

=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/cell_restriction.json
{
  "$schema": "schema.json",
  "includes": ["common/common.json"],
  "background": {
    "texture": "guis/cell_restriction.png",
    "srcRect": [0, 0, 176, 160]
  },
  "text": {
    "dialog_title": {
      "text": {
        "translate": "gui.ae2.CellRestriction"
      },
      "position": {
        "left": 10,
        "top": 8
      }
    },
    "amount_label": {
      "text": {
        "translate": "gui.ae2.CellRestrictionResourceTotal"
      },
      "position": {
        "left": 12,
        "top": 32
      }
    },
    "type_label": {
      "text": {
        "translate": "gui.ae2.Types"
      },
      "position": {
        "left": 126,
        "top": 32
      }
    }
  },
  "widgets": {
    "back": {
      "left": 152,
      "top": -5,
      "width": 20,
      "height": 20
    },
    "amountInput": {
      "left": 12,
      "top": 43,
      "width": 108,
      "height": 12
    },
    "typesInput": {
      "left": 126,
      "top": 43,
      "width": 38,
      "height": 12
    },
    "set": {
      "left": 12,
      "top": 132,
      "width": 48,
      "height": 20
    },
    "release": {
      "left": 66,
      "top": 132,
      "width": 98,
      "height": 20
    }
  }
}

=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/provider_select.json
{
  "$schema": "schema.json",
  "includes": ["common/common.json"],
  "generatedBackground": {
    "width": 260,
    "height": 220
  },
  "text": {
    "dialog_title": {
      "text": {
        "translate": "gui.ae2.ProviderSelect"
      },
      "position": {
        "left": 8,
        "top": 8
      }
    }
  },
  "tooltips": {
    "mapping": {
      "left": 10,
      "top": 192,
      "width": 62,
      "height": 20,
      "tooltip": [
        {
          "translate": "gui.ae2.ProviderSelectMapping"
        },
        {
          "translate": "gui.tooltips.ae2.ProviderSelectMappingBind"
        },
        {
          "translate": "gui.tooltips.ae2.ProviderSelectMappingUnbind"
        },
        {
          "translate": "gui.tooltips.ae2.ProviderSelectMappingBindAndUpload"
        }
      ]
    }
  },
  "widgets": {
    "back": {
      "left": 236,
      "top": -5,
      "width": 20,
      "height": 20
    },
    "search": {
      "left": 10,
      "top": 25,
      "width": 240,
      "height": 12
    },
    "entry0": {
      "left": 10,
      "top": 44,
      "width": 240,
      "height": 20
    },
    "entry1": {
      "left": 10,
      "top": 68,
      "width": 240,
      "height": 20
    },
    "entry2": {
      "left": 10,
      "top": 92,
      "width": 240,
      "height": 20
    },
    "entry3": {
      "left": 10,
      "top": 116,
      "width": 240,
      "height": 20
    },
    "entry4": {
      "left": 10,
      "top": 140,
      "width": 240,
      "height": 20
    },
    "entry5": {
      "left": 10,
      "top": 164,
      "width": 240,
      "height": 20
    },
    "mapping": {
      "left": 10,
      "top": 192,
      "width": 62,
      "height": 20
    },
    "prev": {
      "left": 94,
      "top": 192,
      "width": 30,
      "height": 20
    },
    "next": {
      "left": 136,
      "top": 192,
      "width": 30,
      "height": 20
    },
    "cancel": {
      "left": 188,
      "top": 192,
      "width": 62,
      "height": 20
    }
  }
}

=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/priority_tuner.json
{
  "$schema": "schema.json",
  "includes": [
    "common/common.json"
  ],
  "background": {
    "texture": "guis/priority.png",
    "srcRect": [0, 0, 176, 125]
  },
  "text": {
    "dialog_title": {
      "text": {
        "translate": "gui.ae2.PriorityTuner"
      },
      "position": {
        "left": 8,
        "top": 6
      }
    }
  },
  "widgets": {
    "mode": {
      "left": 60,
      "top": 95,
      "width": 62,
      "height": 20
    },
    "priority": {
      "left": 20,
      "top": 25,
      "width": 138,
      "height": 62
    },
    "priorityInput": {
      "left": 60,
      "top": 50,
      "width": 61,
      "height": 12
    }
  }
}

=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/portable_cell_pickup_filter.json
{
  "$schema": "schema.json",
  "includes": [
    "common/common.json",
    "common/player_inventory.json"
  ],
  "background": {
    "texture": "guis/portable_cell_pickup_filter.png",
    "srcRect": [0, 0, 176, 253]
  },
  "slots": {
    "PORTABLE_CELL_PICKUP_FILTER": {
      "left": 8,
      "top": 29,
      "grid": "BREAK_AFTER_9COLS"
    }
  },
  "text": {
    "dialog_title": {
      "text": {
        "translate": "gui.ae2.PortableCellPickupFilterTitle"
      },
      "position": {
        "left": 8,
        "top": 6
      }
    },
    "player_inventory_title": {
      "text": {
        "translate": "container.inventory"
      },
      "position": {
        "left": 8,
        "bottom": 95
      }
    }
  },
  "widgets": {
    "back": {
      "left": 152,
      "top": -5,
      "width": 20,
      "height": 20
    }
  }
}

=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/cell_workbench.json
{
  "$schema": "schema.json",
  "includes": [
    "common/common.json",
    "common/player_inventory.json",
    "common/toolbox.json"
  ],
  "background": {
    "texture": "guis/cellworkbench.png",
    "srcRect": [0, 0, 176, 253]
  },
  "slots": {
    "STORAGE_CELL": {
      "left": 152,
      "top": 8
    },
    "CONFIG": {
      "left": 8,
      "top": 29,
      "grid": "BREAK_AFTER_9COLS"
    }
  },
  "widgets": {
    "previousPage": {
      "left": 116,
      "top": -5,
      "width": 20,
      "height": 20
    },
    "nextPage": {
      "left": 134,
      "top": -5,
      "width": 20,
      "height": 20
    }
  },
  "text": {
    "dialog_title": {
      "text": {
        "translate": "gui.ae2.CellWorkbench"
      },
      "position": {
        "left": 8,
        "top": 6
      }
    }
  }
}

=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/craft_confirm.json
{
  "$schema": "schema.json",
  "includes": ["common/common.json"],
  "background": {
    "texture": "guis/craftingreport.png",
    "srcRect": [0, 0, 238, 206]
  },
  "text": {
    "dialog_title": {
      "position": {
        "left": 8,
        "top": 7
      }
    },
    "cpu_status": {
      "position": {
        "left": 109,
        "top": 165
      },
      "align": "CENTER"
    }
  },
  "widgets": {
    "scrollbar": {
      "left": 218,
      "top": 19,
      "height": 114
    },
    "selectCpu": {
      "left": 19,
      "bottom": 68,
      "width": 180,
      "height": 20
    },
    "start": {
      "left": 162,
      "bottom": 25,
      "width": 50,
      "height": 20
    },
    "bookmarkMissing": {
      "left": 72,
      "bottom": 25,
      "width": 74,
      "height": 20
    },
    "cancel": {
      "left": 6,
      "bottom": 25,
      "width": 50,
      "height": 20
    },
    "craftTree": {
      "left": 214,
      "top": -5,
      "hideEdge": false,
      "width": 20,
      "height": 20
    }
  }
}

=== FormlessDragon/Applied-Energistics-2-Supergiant/src/main/resources/assets/ae2/screens/set_stock_amount.json
{
  "$schema": "schema.json",
  "includes": ["common/common.json"],
  "background": {
    "texture": "guis/craft_amt.png",
    "srcRect": [0, 0, 176, 107]
  },
  "slots": {
    "MACHINE_OUTPUT": {
      "left": 23,
      "top": 53
    }
  },
  "text": {
    "dialog_title": {
      "text": {
        "translate": "gui.ae2.SelectAmount"
      },
      "position": {
        "left": 8,
        "top": 6
      }
    }
  },
  "widgets": {
    "save": {
      "left": 120,
      "top": 51,
      "width": 38,
      "height": 20
    },
    "back": {
      "left": 152,
      "top": -5,
      "width": 20,
      "height": 20
    },
    "amountToStock": {
      "left": 20,
      "top": 30,
      "width": 138,
      "height": 62
    },
    "amountToStockInput": {
      "left": 48,
      "top": 55,
      "width": 66,
      "height": 12
    },
    "amountToStockPreview": {
      "left": 20,
      "top": 112,
      "width": 138,
      "height": 12
    }
  }
}
